### PR TITLE
Added support for object variables to the plugin SDK

### PR DESCRIPTION
**Pull request by rlaveaux**

### CODE REVIEW

**Comment by rlaveaux** [comment]
Merged

**Comment by miyako** [comment]
the command id ``12112198`` looks odd in #600?

**Comment by rlaveaux** [comment]
Thank you for noticing that. It looks like a typing or copy/paste mistake that went unnoticed.

**Comment by rlaveaux** [comment]
Please note that these changes are not 100% complete since the 4D compiler does not yet understand objects as parameters to a plugin command. But you can test in interpreted mode by using an array parameter "&Y".

The following topics also need to be reviewed by the 4D development team:
- PA_ReturnObjectParameter: Since we can’t return an array or an object, I was unable to test this.
- PA_GetObjectField and PA_SetObjectField: it looks like these are not implemented.

**Comment by laurent-esnault** [comment]
Thank you Rob for this contribution, we appreciate your help. I think this is the right approach. We'll implement some specifics to ease the handling of objects and collections. Your pull request will need some adjustments. Stay tuned!

**Pull request merged**
